version: '2'
services:
    crawler:
        build: 
            context: .
            dockerfile: Dockerfile
        links: 
            - arango
        depends_on:
            - arango
        environment: 
            - ARANGO_HOST_PORT="arango:8529"
    arango:
        image: arangodb:latest
        ports: 
            - '18529:8529'
        volumes_from: 
            - arango_data
        environment: 
            - ARANGO_ROOT_PASSWORD=ir7753nlp!
    arango_data:
        image: ubuntu:xenial
        volumes: 
            - /var/lib/arangodb3
            - /var/lib/arangodb3-apps